using NBomber.CSharp;
using NBomber.Http.CSharp;

[assembly: DoNotParallelize]

namespace Test.Load;

/// <summary>
/// NBomber load scenarios against the TaskItem search and CRUD endpoints, asserting success-rate and
/// P99-latency baselines (95% / under 2000ms for search; 90% for create).
/// Load tier (NBomber): both methods are <c>[Ignore]</c>'d for CI and require a manually-running API host
/// at <c>http://localhost:5000</c>. Faster tiers (Endpoint/E2E) cannot reproduce the concurrent-load
/// behavior these baselines guard.
/// </summary>
[TestClass]
[TestCategory("Load")]
public class TaskItemLoadTests
{
    private const string BaseUrl = "http://localhost:5000";

    [TestMethod]
    [Ignore("Run manually — requires API host running")]
    public void Given_TaskItemSearchEndpoint_When_LoadApplied_Then_MeetsPerformanceBaseline()
    {
        using var httpClient = new HttpClient { BaseAddress = new Uri(BaseUrl) };

        var scenario = Scenario.Create("task-item-search", async context =>
        {
            var request = Http.CreateRequest("GET", $"{BaseUrl}/api/v1/task-items?pageIndex=1&pageSize=20")
                .WithHeader("X-Tenant-Id", Guid.NewGuid().ToString());

            var response = await Http.Send(httpClient, request);
            return response;
        })
        .WithoutWarmUp()
        .WithLoadSimulations(
            Simulation.Inject(rate: 10, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(30))
        );

        var stats = NBomberRunner
            .RegisterScenarios(scenario)
            .WithReportFolder("load-reports")
            .Run();

        var scenarioStats = stats.ScenarioStats[0];
        Assert.IsGreaterThanOrEqualTo(scenarioStats.Ok.Request.Percent, 95.0,
            $"Success rate {scenarioStats.Ok.Request.Percent}% below 95% threshold");
        Assert.IsLessThan(scenarioStats.Ok.Latency.Percent99, 2000.0,
            $"P99 latency {scenarioStats.Ok.Latency.Percent99}ms exceeds 2000ms threshold");
    }

    [TestMethod]
    [Ignore("Run manually — requires API host running")]
    public void Given_TaskItemCrudEndpoints_When_LoadApplied_Then_MeetsThroughputBaseline()
    {
        using var httpClient = new HttpClient { BaseAddress = new Uri(BaseUrl) };

        var createScenario = Scenario.Create("task-item-create", async context =>
        {
            var body = $$"""
            {
                "title": "Load test task {{context.ScenarioInfo.InstanceNumber}}-{{context.InvocationNumber}}",
                "description": "Generated by load test",
                "status": "Open",
                "priority": "Medium"
            }
            """;

            var request = Http.CreateRequest("POST", $"{BaseUrl}/api/v1/task-items")
                .WithHeader("X-Tenant-Id", Guid.NewGuid().ToString())
                .WithHeader("Content-Type", "application/json")
                .WithBody(new StringContent(body, System.Text.Encoding.UTF8, "application/json"));

            var response = await Http.Send(httpClient, request);
            return response;
        })
        .WithoutWarmUp()
        .WithLoadSimulations(
            Simulation.Inject(rate: 5, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(30))
        );

        var stats = NBomberRunner
            .RegisterScenarios(createScenario)
            .WithReportFolder("load-reports")
            .Run();

        var scenarioStats = stats.ScenarioStats[0];
        Assert.IsGreaterThanOrEqualTo(scenarioStats.Ok.Request.Percent, 90.0,
            $"Create success rate {scenarioStats.Ok.Request.Percent}% below 90% threshold");
    }
}
