// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Infrastructure.Data;

#nullable disable

namespace TaskFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaskFlowDbContextTrxn))]
    partial class TaskFlowDbContextTrxnModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("taskflow")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Domain.Model.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("IX_Attachment_OwnerType_OwnerId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_Attachment_TenantId_Id");

                    b.ToTable("Attachment", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Category_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_TenantId_Name");

                    b.ToTable("Category", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("TaskItemId");

                    b.HasIndex("TenantId", "TaskItemId")
                        .HasDatabaseName("CIX_ChecklistItem_TenantId_TaskItemId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TenantId", "TaskItemId"));

                    b.ToTable("ChecklistItem", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("TaskItemId");

                    b.HasIndex("TenantId", "TaskItemId")
                        .HasDatabaseName("CIX_Comment_TenantId_TaskItemId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TenantId", "TaskItemId"));

                    b.ToTable("Comment", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Tag_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tag_TenantId_Name");

                    b.ToTable("Tag", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Features")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentTaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_TaskItem_CategoryId");

                    b.HasIndex("ParentTaskItemId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TaskItem_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TaskItem_Status");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_TaskItem_TenantId_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TenantId", "Id"));

                    b.ToTable("TaskItem", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("TagId");

                    b.HasIndex("TaskItemId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskItemTag_TaskItemId_TagId");

                    b.HasIndex("TenantId", "TaskItemId")
                        .HasDatabaseName("CIX_TaskItemTag_TenantId_TaskItemId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TenantId", "TaskItemId"));

                    b.ToTable("TaskItemTag", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.ChecklistItem", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Comment", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("Comments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Category", "Category")
                        .WithMany("TaskItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "ParentTaskItem")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("TaskFlow.Domain.Model.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("DueDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("DueDate");

                            b1.Property<DateTimeOffset?>("StartDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("StartDate");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem", "taskflow");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaskFlow.Domain.Model.ValueObjects.RecurrencePattern", "RecurrencePattern", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("EndDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("RecurrenceEndDate");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("RecurrenceFrequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("int")
                                .HasColumnName("RecurrenceInterval");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem", "taskflow");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("Category");

                    b.Navigation("DateRange")
                        .IsRequired();

                    b.Navigation("ParentTaskItem");

                    b.Navigation("RecurrencePattern");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItemTag", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Tag", "Tag")
                        .WithMany("TaskItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("TaskItemTags")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Tag", b =>
                {
                    b.Navigation("TaskItemTags");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Comments");

                    b.Navigation("SubTasks");

                    b.Navigation("TaskItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
